In [1]:
import torch
import torch.nn as nn
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
!pip install torchinfo

In [4]:
from torchinfo import summary

In [98]:
X_train.shape

torch.Size([455, 30])

In [97]:
summary(model, input_size=(455,30))

Layer (type:depth-idx)                   Output Shape              Param #
MyModel                                  [455, 1]                  --
├─Sequential: 1-1                        [455, 1]                  --
│    └─Linear: 2-1                       [455, 15]                 465
│    └─ReLU: 2-2                         [455, 15]                 --
│    └─Linear: 2-3                       [455, 8]                  128
│    └─ReLU: 2-4                         [455, 8]                  --
│    └─Linear: 2-5                       [455, 4]                  36
│    └─ReLU: 2-6                         [455, 4]                  --
│    └─Linear: 2-7                       [455, 1]                  5
│    └─Sigmoid: 2-8                      [455, 1]                  --
Total params: 634
Trainable params: 634
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.29
Input size (MB): 0.05
Forward/backward pass size (MB): 0.10
Params size (MB): 0.00
Estimated Total Size (MB): 0.16

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [6]:
backup = df.copy()

In [7]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### Train Test split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size = 0.2)

### Scaling and encoding

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455,) (114,)


In [12]:
y_train = y_train.reshape(-1,1)
y_test = y_test.reshape(-1,1)

In [13]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455, 1) (114, 1)


In [14]:
X_train = torch.from_numpy(X_train).float()
X_test = torch.from_numpy(X_test).float()
y_train = torch.from_numpy(y_train).float()
y_test = torch.from_numpy(y_test).float()

## Creating Model

In [103]:
class MyModel(nn.Module):
  def __init__(self, input_features):
    super().__init__()
    self.network = nn.Sequential(
        nn.Linear(input_features, 15),
        nn.ReLU(),
        nn.Linear(15, 8),
        nn.ReLU(),
        nn.Linear(8, 4),
        nn.ReLU(),
        nn.Linear(4, 1),
        nn.Sigmoid()
    )

  def forward(self, X):
    out = self.network(X)
    return out


  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)


    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

  def predict(self, X):
    with torch.no_grad():
      y_pred = self.forward(X)
      y_pred = (y_pred > 0.5).float()
      return y_pred

In [104]:
model = MyModel(X_train.shape[1])

In [87]:
learning_rate = 10
epochs = 1000

In [100]:
model.network[0].weight.shape

torch.Size([15, 30])

In [88]:
y_before = model.predict(X_train)
y_before.sum()

tensor(0.)

In [89]:
# Loop
for epoch in range(epochs):
  y_pred = model(X_train)
  loss = model.loss_function(y_pred, y_train)
  loss.backward()

  with torch.no_grad():
    for param in model.parameters():
      param -= learning_rate * param.grad
      param.grad.zero_()

  if epoch % 100 == 0:
    print(f"Epoch: {epoch} Loss: {loss}")

Epoch: 0 Loss: 0.6567490100860596
Epoch: 100 Loss: 8.626778602600098
Epoch: 200 Loss: 8.626778602600098
Epoch: 300 Loss: 8.626778602600098
Epoch: 400 Loss: 8.626778602600098
Epoch: 500 Loss: 8.626778602600098
Epoch: 600 Loss: 8.626778602600098
Epoch: 700 Loss: 8.626778602600098
Epoch: 800 Loss: 8.626778602600098
Epoch: 900 Loss: 8.626778602600098


In [62]:
z1 = torch.matmul(X_train,torch.transpose(model.network[0].weight, 1, 0)) + model.network[0].bias
a1 = torch.relu(z1)
z2 = torch.matmul(a1, torch.transpose(model.network[2].weight, 1, 0)) + model.network[2].bias
a2 = torch.relu(z2)
z3 = torch.matmul(a2, torch.transpose(model.network[4].weight, 1, 0)) + model.network[4].bias
a3 = torch.relu(z3)
z4 = torch.matmul(a3, torch.transpose(model.network[6].weight, 1, 0)) + model.network[6].bias
a4 = torch.sigmoid(z4)

In [90]:
y_after = model.predict(X_train)
print(f'{y_after.sum()=} , {y_train.sum()=}')

y_after.sum()=tensor(381.) , y_train.sum()=tensor(173.)


In [91]:
y_compare = (y_after == y_train).float()
print(f'{y_compare.sum()=} , {y_train.shape[0]=}')

y_compare.sum()=tensor(177.) , y_train.shape[0]=455


In [92]:
y_test_pred = model.predict(X_test)
print(f'{y_test_pred.sum()=} , {y_test.sum()=}')

y_test_pred.sum()=tensor(94.) , y_test.sum()=tensor(39.)


In [93]:
y_test_compare = (y_test_pred == y_test).float()
print(f'{y_test_compare.sum()}, {y_test_compare.shape[0]}')

43.0, 114


In [67]:
z1

tensor([[-0.2343,  0.6056,  0.7273,  ...,  0.6571,  0.9324,  0.5623],
        [-0.2031, -0.0963,  0.0054,  ..., -0.2924, -0.1030,  0.0036],
        [-0.4594, -0.4752, -0.1997,  ...,  0.1493,  0.3402, -0.1468],
        ...,
        [-0.4573, -0.2491, -0.6001,  ..., -0.2181,  0.6113, -0.2441],
        [ 0.1860,  0.1411, -0.4351,  ..., -0.2425, -0.5102, -0.5047],
        [-0.6585,  0.0411,  0.1446,  ...,  0.2540,  0.2493,  0.3673]],
       grad_fn=<AddBackward0>)

In [68]:
a1

tensor([[0.0000, 0.6056, 0.7273,  ..., 0.6571, 0.9324, 0.5623],
        [0.0000, 0.0000, 0.0054,  ..., 0.0000, 0.0000, 0.0036],
        [0.0000, 0.0000, 0.0000,  ..., 0.1493, 0.3402, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.6113, 0.0000],
        [0.1860, 0.1411, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0411, 0.1446,  ..., 0.2540, 0.2493, 0.3673]],
       grad_fn=<ReluBackward0>)

In [69]:
z2

tensor([[-0.1213,  0.3644, -0.3735,  ..., -0.2046, -0.3770, -0.0115],
        [ 0.1727, -0.0024, -0.0353,  ...,  0.1388, -0.1786,  0.1881],
        [ 0.1832,  0.1001, -0.1979,  ...,  0.0891, -0.2297,  0.0141],
        ...,
        [ 0.0009,  0.2201, -0.3270,  ..., -0.1598, -0.4642,  0.0131],
        [-0.0460, -0.0532,  0.0718,  ...,  0.1585,  0.0349,  0.0202],
        [ 0.0129,  0.1076, -0.0858,  ...,  0.1931, -0.0623, -0.0382]],
       grad_fn=<AddBackward0>)

In [70]:
a2

tensor([[0.0000, 0.3644, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.1727, 0.0000, 0.0000,  ..., 0.1388, 0.0000, 0.1881],
        [0.1832, 0.1001, 0.0000,  ..., 0.0891, 0.0000, 0.0141],
        ...,
        [0.0009, 0.2201, 0.0000,  ..., 0.0000, 0.0000, 0.0131],
        [0.0000, 0.0000, 0.0718,  ..., 0.1585, 0.0349, 0.0202],
        [0.0129, 0.1076, 0.0000,  ..., 0.1931, 0.0000, 0.0000]],
       grad_fn=<ReluBackward0>)

In [71]:
z3

tensor([[ 0.2362,  0.2637, -0.2980, -0.2988],
        [ 0.2041,  0.2388, -0.2517, -0.2279],
        [ 0.2125,  0.1612, -0.3087, -0.2744],
        ...,
        [ 0.1941,  0.1957, -0.3038, -0.3420],
        [ 0.2500,  0.2540, -0.2943, -0.2901],
        [ 0.2433,  0.2773, -0.2907, -0.2696]], grad_fn=<AddBackward0>)

In [72]:
a3

tensor([[0.2362, 0.2637, 0.0000, 0.0000],
        [0.2041, 0.2388, 0.0000, 0.0000],
        [0.2125, 0.1612, 0.0000, 0.0000],
        ...,
        [0.1941, 0.1957, 0.0000, 0.0000],
        [0.2500, 0.2540, 0.0000, 0.0000],
        [0.2433, 0.2773, 0.0000, 0.0000]], grad_fn=<ReluBackward0>)

In [60]:
model.network[0].bias

Parameter containing:
tensor([-0.1456,  0.0309,  0.0998,  0.0292,  0.0027,  0.0858, -0.1205, -0.0598,
         0.1232,  0.0246, -0.0475,  0.0779,  0.1273,  0.1699,  0.1000],
       requires_grad=True)

In [61]:
model.network[2].bias

Parameter containing:
tensor([-0.1124,  0.0197,  0.0256,  0.0807, -0.1800,  0.2423,  0.1774, -0.0800],
       requires_grad=True)

In [62]:
model.network[4].bias

Parameter containing:
tensor([ 0.2857,  0.3059, -0.3212, -0.3084], requires_grad=True)

In [63]:
model.network[6].bias

Parameter containing:
tensor([0.3246], requires_grad=True)

In [105]:
for param in model.parameters():
  print(param)

Parameter containing:
tensor([[-0.1716,  0.0792, -0.1711, -0.1456,  0.0612,  0.1708, -0.1244, -0.0022,
          0.1781, -0.1482, -0.1759, -0.1450, -0.1213,  0.1741,  0.1661, -0.1715,
          0.1689, -0.0555,  0.0138, -0.1288, -0.1374,  0.0976, -0.0260, -0.0026,
         -0.1565, -0.0791, -0.1292, -0.0066, -0.0891,  0.0490],
        [ 0.1552, -0.0845, -0.0823,  0.1472, -0.1371,  0.0692, -0.0820, -0.1698,
          0.1748,  0.0635, -0.0652,  0.0564,  0.0707, -0.0358, -0.0025,  0.1332,
          0.0386,  0.0717,  0.0266, -0.0667, -0.0495,  0.0826,  0.0138,  0.0181,
         -0.1483, -0.0205,  0.0464, -0.1780, -0.1372, -0.0210],
        [ 0.0210,  0.1184,  0.0784, -0.1712, -0.1166, -0.0357, -0.0365,  0.1619,
          0.0609, -0.1065,  0.0036,  0.1482,  0.1169,  0.0740,  0.0485,  0.0716,
          0.1356, -0.0767,  0.1452, -0.0801,  0.1420,  0.0707, -0.0337,  0.1479,
          0.1653,  0.0223,  0.0631, -0.0015, -0.1725,  0.0717],
        [-0.1402,  0.0990,  0.0691, -0.1265,  0.1464, -0.